# Generated by Django 3.0.2 on 2021-03-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_created=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('adi', models.CharField(max_length=255, verbose_name='Adi')),
                ('slug', models.SlugField(editable=False, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategori Yönetimi',
                'ordering': ['-create_at'],
            },
        ),
    ]
