# Generated by Django 3.0.2 on 2021-03-01 18:27

import ckeditor.fields
from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hakkimda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(max_length=255, verbose_name='Facebook ')),
                ('twitter', models.CharField(max_length=255, verbose_name='Twitter ')),
                ('github', models.CharField(max_length=255, verbose_name='GitHub ')),
                ('linked', models.CharField(max_length=255, verbose_name='Linkedin ')),
                ('telefon', models.CharField(max_length=255, verbose_name='Telefon ')),
                ('email', models.CharField(max_length=255, verbose_name='E-Mail ')),
                ('hakkimda', ckeditor.fields.RichTextField(verbose_name='Hakkımda ')),
                ('profil', models.ImageField(upload_to=home.models.content_file_name_dosyalar, verbose_name='Profil ')),
            ],
            options={
                'verbose_name': 'Hakkımda',
                'verbose_name_plural': 'Hakkımda Yönet',
                'db_table': 'hakkimdatb',
            },
        ),
        migrations.CreateModel(
            name='IlgiAlanlari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aciklama', ckeditor.fields.RichTextField(verbose_name='İlgi Alanları ')),
            ],
            options={
                'verbose_name': 'İlgi Alanları',
                'verbose_name_plural': 'İlgi Alanlarını Yönet',
                'db_table': 'ilgialanitb',
            },
        ),
        migrations.CreateModel(
            name='KullandigimTeknolojiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=255, verbose_name='Adi ')),
                ('icon', models.CharField(max_length=255, verbose_name='İcon ')),
            ],
            options={
                'verbose_name': 'Kullanıcı Teknolojileri',
                'verbose_name_plural': 'Kullanıcı Teknolojileri Yönet',
                'db_table': 'kteknolojileritb',
            },
        ),
        migrations.CreateModel(
            name='Projeler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=255, verbose_name='Adi ')),
                ('sirket', models.CharField(max_length=255, verbose_name='Şirket ')),
                ('icerik', ckeditor.fields.RichTextField(verbose_name='İçerik ')),
                ('baslangicTarihi', models.DateField(default=home.models.default_value_current_today, verbose_name='Başlangıç Tarihi ')),
                ('bitisTarihi', models.DateField(default=None, verbose_name='Bitiş Tarihi ')),
            ],
            options={
                'verbose_name': 'Projeler',
                'verbose_name_plural': 'Projeleri Yönet',
                'db_table': 'projetb',
            },
        ),
    ]
