# Generated by Django 3.0.2 on 2021-03-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Egitim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('okulismi', models.CharField(max_length=255, verbose_name='Okul İsmi ')),
                ('baslangictarihi', models.DateField(verbose_name='Başlangıç Tarihi ')),
                ('bitistarihi', models.DateField(verbose_name='Bitiş Tarihi')),
            ],
            options={
                'verbose_name': 'Eğitim',
                'verbose_name_plural': 'Eğitim',
                'db_table': 'egitimtb',
            },
        ),
    ]
