# Generated by Django 3.0.2 on 2021-03-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_egitim'),
    ]

    operations = [
        migrations.AddField(
            model_name='egitim',
            name='alan',
            field=models.CharField(default=1, max_length=255, verbose_name='Alan'),
            preserve_default=False,
        ),
    ]
